development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: cuauh_development
  pool: 5
  timeout: 5000
  username: pitagoras
  password: password

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  timeout: 5000
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_USER'] %>